apiVersion: v1
kind: ConfigMap
metadata:
  name: searxng-config
  namespace: search-infrastructure
data:
  settings.yml: |
    use_default_settings: true

    server:
      limiter: false
      public_instance: false
      bind_address: "0.0.0.0"
      port: 8080

    search:
      formats:
        - html
        - json
